config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new', as: 'tasks_new'
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= @task.title %></h1>
<%= form_with model: @task, url: task_path(@task), method: :patch do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :details %>
  <%= form.text_area :details %><br>

  <%= form.label :completed %>
  <%= form.check_box :completed %><br>

  <%= form.submit "Update Task" %>
<% end %>
<%= link_to "Back to task", task_path %>

app/views/tasks/index.html.erb
<%= javascript_include_tag 'application' %>
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %>
      <%= form_with model: task, url: destroy_task_path(task), method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr de vouloir supprimer cette tâche ?' } do |form| %>
        <%= form.submit "Supprimer", class: "delete-button" %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Add task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task, url: tasks_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :details %>
  <%= form.text_area :details %><br>

  <%= form.label :completed %>
  <%= form.check_box :completed %><br>

  <%= form.submit "Create" %>
<% end %>
<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %> </h1>
<%= link_to "Edit this task", edit_task_path %>

<p><%= @task.details %></p>

<%= link_to "Back to list", tasks_path %>